### ISSUE TITLE
Server did not start automatically after client startup

### ISSUE THREAD

**Issue by M4X1K02** [AlexisN94/Skyscraper#1]
Environment:
Windows 10 Home, 19044.2486

I followed the installation instructions, but after I ran start.bat only the client seemed to start. A checkup on the console showed that the server was not running.
Manually opening another terminal and starting the server resolved this issue.

Aside from that, really great work! The UI looks fantastic, I am very eager to see this project evolve.

**Comment by AlexisN94** [comment]
Thank you for the feedback, I'll look into it
By the way, I just pushed a bugfix so you might want to pull again

**Comment by AlexisN94** [comment]
Windows scripts have been fixed
