### ISSUE TITLE
Not able to search for flights

### ISSUE THREAD

**Issue by priyeshj12** [AlexisN94/Skyscraper#3]
When searching for flights the program immediately pauses, this happens with every flight combination.
![image](https://user-images.githubusercontent.com/46448521/216729146-bc440235-6fd7-4216-8ae7-73f108e85e70.png)

**Comment by AlexisN94** [comment]
Hi. Are you sure the backend is running?

**Comment by priyeshj12** [comment]
Don't think so: 
![image](https://user-images.githubusercontent.com/46448521/216730740-33351503-6280-44f7-988f-1adc119de575.png)
Does it need to be enabled manually by any chance?

**Comment by AlexisN94** [comment]
I've updated the Windows scripts. It should work now, please confirm.

**Comment by M4X1K02** [comment]
I can confirm that it works now out of the box
